### ISSUE TITLE
Error "multi_gpu_model" not found

### ISSUE THREAD

**Issue by Unity123** [minimaxir/textgenrnn#222]
Whenever I try to import textgenrnn, it gives me that error. I've tested it on colab, and it works fine there when I set it to tensorflow 1.x but throws the error in 2.x. But the latest version of textgenrnn doesn't support 1.x, so please fix this!

**Comment by thedominica** [comment]
I am getting these even on google collab

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-e4495ab1e79a> in <module>()
      1 get_ipython().system('pip install -q textgenrnn')
      2 from google.colab import files
----> 3 from textgenrnn import textgenrnn
      4 from datetime import datetime
      5 import os

1 frames
/usr/local/lib/python3.6/dist-packages/textgenrnn/textgenrnn.py in <module>()
      3 from keras.preprocessing import sequence
      4 from keras.preprocessing.text import Tokenizer, text_to_word_sequence
----> 5 from keras.utils import multi_gpu_model
      6 from keras.optimizers import RMSprop
      7 from keras import backend as K

ImportError: cannot import name 'multi_gpu_model'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by 2PacIsAlive** [comment]
the package seems totally broken right now because of this.. try a fresh install yourself

**Comment by gabedanon** [comment]
Hello, I had this error and was able to bypass by downgrading from TensorFlow 2.4.x to 2.3.2: `pip3 install tensorflow==2.3.2`

**Comment by gaben5841** [comment]
I'd very much like to use 2.4 with my project, but it always throws this error with it. Hope we can find a solution.

**Comment by 1siddharth** [comment]
cannot import name 'multi_gpu_model' from 'keras.utils' it shows me this error

**Comment by ZhaoqingT** [comment]
I just commented the import line for it is not used in the whole file.

**Comment by 1siddharth** [comment]
I downgraded the tensorflow and keras (keras==2.3.0  tensorflow-gpu==2.3.2) with python 3.7.9 and it works fine now ..!

**Comment by allo-** [comment]
This is still an issue and there is no tensorflow 2.3.x for python3.9 (on pypi) and for example Debian only packages python3.9 in their upcoming release.

**Comment by fernaoguerra** [comment]
I got the same error on python 3.82
I tried downgrading to tensorflow==2.3.2 but now I got this other error:
"AttributeError: module 'tensorflow.compat.v2' has no attribute '__internal__'"
Did anyone got it working on 3.8?

**Comment by fernaoguerra** [comment]
Ok. Everything solved for me once I installed directly from the github repo:
**pip3 install git+git://github.com/minimaxir/textgenrnn.git**

**Comment by mytran2111** [comment]
> I just commented the import line for it is not used in the whole file.

Yeah but isnt the error occur when we import textgenrnn?

**Comment by Sabadon** [comment]
> 
> 
> Ok. Everything solved for me once I installed directly from the github repo:
> **pip3 install git+git://github.com/minimaxir/textgenrnn.git**

OH MAN, i love you <3
It work fine to me

**Comment by minimaxir** [comment]
I was pinged about this issue so I set the Colab notebook to the workaround noted.

Not entirely sure if there's an easy fix because dependency issues are unfun.

**Comment by mattallinson** [comment]
> I was pinged about this issue so I set the Colab notebook to the workaround noted.
> 
> Not entirely sure if there's an easy fix because dependency issues are unfun.

Not sure if I'm being an idiot or not as I don't know how pip actually works, but the version currently on GitHub works fine (at least for me and presumably everyone else celebrating on @fernaoguerra's comment) which is more recent (April 2020) than the version currently available on PyPI/pip (Feb 2020) so is the solution simply not to make the most current version on GitHub the one that installs through pip?

**Comment by Aergonus** [comment]
The `multi_gpu_model` import was removed in current master so installing from source works fine. 
Looks like it was moved to its own [utils](https://github.com/tensorflow/tensorflow/blob/r2.5/tensorflow/python/keras/utils/all_utils.py#L34)

updating the published version in pip would solve this going forward, if the project had CI this could have been caught before publishing a non-working version

**Comment by Aillian** [comment]
i was able to solve this issue by going to the textgenrnn.py file and change `from tensorflow.python.keras.utils import multi_gpu_model` to `from tensorflow.python.keras.utils.multi_gpu_utils import multi_gpu_model`

**Comment by FireHead90544** [comment]
Usually, it is not advised to edit the module itself.
But you need to edit the module itself and change the `multi_gpu_module` and `set_session` import lines to these
```py
from tensorflow.python.keras.utils.multi_gpu_utils import multi_gpu_model
from keras.backend import set_session
```
Though, the changes should be done to the module in a PR and new update should be released to PyPI

**Comment by renning1205** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，邮件已收到，尽快回复。

**Comment by FlashlightET** [comment]
Tensorflow sucks ass. Someone needs to fix it. Tensorflow,  not textgenrnn.

**Comment by ioiste** [comment]
> Ok. Everything solved for me once I installed directly from the github repo: **pip3 install git+git://github.com/minimaxir/textgenrnn.git**

Thank you!
In Google Colab I had to do this a little different:
`!pip3 install textgenrnn@git+https://github.com/minimaxir/textgenrnn.git@master`

**Comment by renning1205** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，邮件已收到，尽快回复。

**Comment by pimentoliver** [comment]
Hello, has anyone had this issue again recently and resolved it? tensorflow==2.3.2 is deprecated, installing directly from git isn't working, and updating tensorflow + keras also did not work out for me

**Comment by renning1205** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，邮件已收到，尽快回复。

**Comment by MaraJadeLives** [comment]
There's an easy fix, if you don't mind losing multi gpu compatibility. Look for where it's looking for multi_gpu_model.py, and make a .py file with a comment in it, there, to hide that error, because it find what it's looking for. I am just training on CPU, and none of my boards support more than one GPU, so that's what I do.

**Comment by allo-** [comment]
What python and tensorflow version are you using? I have the problem, that it seems to get worse with newer python/cuda/tensorflow versions to get it to run and currently I use a virtual environment with outdated libraries which may even stop working with python 3.11 and later versions.

**Comment by jasminefederer** [comment]
any updates on this? what needs to be changed in google colab notebook to bypass these errors?

**Comment by MaraJadeLives** [comment]
I know I should share my changes, but I made a fork of textgenrnn, and put
my changes in it.

**Comment by MaraJadeLives** [comment]
No idea what you'd need to change in colab.
