### ISSUE TITLE
TypeError: softmax() got an unexpected keyword argument 'axis'

### ISSUE THREAD

**Issue by awfssv** [minimaxir/textgenrnn#18]
Dear,

My environment as below:
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.
1900 64 bit (AMD64)] on win32

I received below error when I issue textgenrnn():

>>> textgen = textgenrnn()
2018-04-27 09:39:11.639683: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\
35\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn
't compiled to use AVX instructions, but these are available on your machine and
 could speed up CPU computations.
2018-04-27 09:39:11.640683: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\
35\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn
't compiled to use AVX2 instructions, but these are available on your machine an
d could speed up CPU computations.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Anaconda3\lib\site-packages\textgenrnn\textgenrnn.py",
line 59, in __init__
    weights_path=weights_path)
  File "C:\Program Files\Anaconda3\lib\site-packages\textgenrnn\model.py", line
29, in textgenrnn_model
    output = Dense(num_classes, name='output', activation='softmax')(attention)
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\engine\topology.py",
line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\layers\core.py", line
 881, in call
    output = self.activation(output)
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\activations.py", line
 29, in softmax
    return K.softmax(x)
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\backend\tensorflow_ba
ckend.py", line 2963, in softmax
    return tf.nn.softmax(x, axis=axis)
TypeError: softmax() got an unexpected keyword argument 'axis'
>>>

**Comment by minimaxir** [comment]
What version of TensorFlow are you using? It seems like you are using an older version which may be causing this issue.

**Comment by awfssv** [comment]
Hi minimaxir,
I'm using tensorflow (1.3.0), It's ok after I updated tensorflow to v1.5.1.
Thank you very much.
